### ISSUE TITLE
Compact arrangement of the "time" string

### ISSUE THREAD

**Issue by snooppr** [benhsm/minesweeper#1]
The game works in Termux, but when you zoom in or select a high difficulty level, you must force the zoom out, it becomes uncomfortable on phones.

Scale bug: field offset:
![min](https://user-images.githubusercontent.com/61022210/196868186-de8a453b-20cb-420e-99bf-55a5b1e15b62.gif)

**Comment by benhsm** [comment]
Looks like this was fixed upstream: https://github.com/charmbracelet/bubbletea/commit/a7067fbfa2ed2cb89b3eeff1bde9ccd1870765aa

I've updated the version of BubbleTea used to the current `master` state, and it seems to correct this particular bug, as far as I can tell. In the current version, lines that don't fit the terminal height should just be stripped from the top of the render output.

I hadn't anticipated that this would be used in Termux, but I'm glad that it is. I'm not sure what to do to make the higher difficulty levels more playable on phone screens. I'm thinking maybe I'll try to make the playing field function like a scrollable viewport. Please feel free to open further issues if you have any ideas about this!
